name: Publish

on: push

jobs:
  packsquash:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # A non-shallow repository clone is required

      - name: Make Optimized Pack
        uses: ComunidadAylas/PackSquash-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_optifine_mod: true
          never_store_squash_times: true
          path: ./

      - name: DownloadArtifact Optimized Pack
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Rename Optimized Pack
        run: |
          mv ./pack.zip "xali's Enchanted Books v0.12.0.zip"

      - name: Delete Artifact 
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Optimized pack

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: Srw5RQ6k
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 513425
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: ${{ steps.info.outputs.package }}.zip
          name: ${{ steps.info.outputs.name }} v${{ steps.info.outputs.version }}
          version: v${{ steps.info.outputs.version }}
          version-type: release
          changelog-file: CHANGELOG.md
          game-versions: |
            1.20
            1.19.3
            1.19.2
            1.19.1
            1.19
            1.18.2
            1.18.1
            1.18
            1.17.1
            1.17
            1.16.5
            1.16.4
            1.16.3
            1.16.2
            1.16.1
            1.16
            1.15.2
            1.15.1
            1.15
            1.14.4
            1.14.3
            1.14.2
            1.14.1
            1.14
            1.13.2
            1.13.1
            1.13
          loaders: |
            minecraft